### ISSUE TITLE
Different Port

### ISSUE THREAD

**Issue by muhammedaligunes** [magkopian/pic-xc8-lcd-library#1]
How can ı use this library with different data ports ?
D4 RC0
D5 RC1
D6 RB1
D7 RA4

**Comment by magkopian** [comment]
Unfortunately, the way this library was written doing that is just not possible. If you look at the `lcd.c` you can see that I'm doing logic operations directly on the port. In order for what you ask to work, the whole library would have to be rewritten.

**Comment by silvioprog** [comment]
Hello @muhammedaligunes and @magkopian . Some time ago I made a macro based library using a logic inspired in awesome [`pic-xc8-lcd-library`](https://github.com/risoflora/brook4xc8/blob/master/src/b4x_lcd.c#L29) and the port declaration syntax inspired in [mikroC](https://download.mikroe.com/documents/compilers/mikroc/pic/help/lcd_library.htm)'s LCD library:

```c
#include <b4x_macros.h>
#include <b4x_lcd.h>

B4X_LCD_SET_RS(PORTB, 0); /* Set LCD RS port. */
B4X_LCD_SET_E(PORTB, 1); /* Set LCD E port. */
B4X_LCD_SET_D4(RC, 0); /* Set LCD D4 port. */
B4X_LCD_SET_D5(RC, 1); /* Set LCD D5 port. */
B4X_LCD_SET_D6(RB, 1); /* Set LCD D6 port. */
B4X_LCD_SET_D7(RA, 4); /* Set LCD D7 port. */

void main() {
    CMCON = 0x07; /* Disable comparator. */
    TRISB = 0xc0; /* RB<5:0> as output. */
    b4x_lcd_init(); /* Initialize LCD. */
    b4x_lcd_write(0, 0, "HELLO WORLD!"); /* Writes "HELLO WORLD!" on the LCD. */
    B4X_RUN(); /* Main loop. */
}
```

and an another way to specify the ports (closest to mikroC syntax):

```c
B4X_LCD_D4 B4X_AT(RC, 0)
B4X_LCD_D5 B4X_AT(RC, 1);
B4X_LCD_D6 B4X_AT(RB, 1);
B4X_LCD_D7 B4X_AT(RA, 4);
```

You can download and see other modules/examples of the library at: https://github.com/risoflora/brook4xc8 .

**Comment by magkopian** [comment]
@silvioprog Thank you for sharing this. I hope others will also find it useful.

**Comment by silvioprog** [comment]
I thank you dude! :-)
